---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: tauser
   remote_user: tauser
   become: yes
   become_method: sudo

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
